kill_signal = "SIGINT"
kill_timeout = 5

[env]
PORT = "8080"
ALLOW_ALL_ORIGINS = "yes"

[[services]]
internal_port = 8080
protocol = "tcp"

[services.concurrency]
hard_limit = 500
soft_limit = 300

[[services.ports]]
handlers = ["http"]
port = "80"

[[services.ports]]
handlers = ["tls", "http"]
port = "443"
